version: '3.8'

services:
  db:
    container_name: go-mysql-demo
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=demoproject
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '33009:3306'
    volumes:
      - go-mysql:/var/lib/mysql
    

volumes:
  go-mysql:
    driver: local